import React from "react";
import styles from "./ERPScrollSection.module.css";

const ERPScrollSection = () => {
  const content = [
    {
      title: " Finance Management",
      description: "Automating accounting, budgeting, and financial reporting is a powerful solution that streamlines financial management by eliminating manual processes, reducing errors, and ensuring timely, accurate, and comprehensive financial data. Automated accounting systems can handle a wide range of tasks such as recording transactions, categorizing expenses, reconciling bank statements, and managing accounts payable and receivable, all while adhering to the established chart of accounts. This reduces the workload on accounting teams and ensures consistency in financial records. Budgeting automation allows businesses to create dynamic, real-time budgets that can adapt to changing financial conditions. By automatically pulling data from various financial sources, such as past expenditures, forecasts, and current performance, these systems enable businesses to set more accurate budgetary targets, track actual spending, and identify variances without manual intervention. This ensures that companies stay within budget and can make adjustments quickly to avoid overspending or underfunding in key areas. Automated financial reporting generates real-time, customized reports that provide valuable insights into financial performance, profitability, liquidity, and operational efficiency. These reports, which can range from balance sheets and income statements to cash flow and tax reports, are generated without manual data entry, reducing the risk of human error and improving data accuracy. Automation also allows businesses to create financial forecasts based on historical data, trends, and predictive analytics, empowering decision-makers with the information they need to plan for future growth and make informed financial decisions. Additionally, integration with other enterprise systems such as payroll, sales, and inventory management ensures that all financial data is synchronized across the business, creating a unified view of financial health. By automating these core financial functions, businesses can improve operational efficiency, enhance financial visibility, ensure compliance with accounting standards, and focus more resources on strategic activities that drive growth and profitability. Ultimately, automation in accounting, budgeting, and financial reporting enhances productivity, mitigates risks, and strengthens the overall financial management process.",
      buttonText: "Learn More",
    },
    {
      title: " Human Resource",
      description: "Managing payroll, recruitment, and employee data through an integrated system enhances organizational efficiency by centralizing key HR processes and ensuring accurate, timely execution of critical functions. Payroll management involves calculating employee salaries, bonuses, deductions, and tax withholdings, and automating these tasks ensures that employees are paid on time, in full, and in compliance with regulatory requirements. By eliminating manual calculations, the system reduces errors and streamlines the payroll process, making it easier for HR teams to handle complex pay structures, overtime, and benefits administration. Recruitment processes are equally streamlined by automating the collection and processing of job applications, candidate screenings, interview scheduling, and onboarding. Automated tools can assess resumes, match candidates to job requirements, and track the status of each candidate in the hiring pipeline, reducing the time spent on manual sorting and enhancing the candidate experience. Once an employee is hired, the system manages employee data in a secure, organized manner, including personal information, job titles, performance records, benefits enrollment, and training histories. By centralizing this information, HR departments can quickly access and update employee profiles, improving the efficiency of day-to-day operations and ensuring that data is consistent and accurate. The system can also handle compliance with labor laws, ensuring that employee records are up to date and meet legal requirements, such as work permits, tax filings, and benefits contributions. Integration with time-tracking and attendance systems ensures that payroll calculations reflect accurate work hours, absenteeism, and leave records, further automating and aligning employee compensation. Moreover, HR analytics tools integrated into the system can generate insights into employee performance, turnover rates, compensation trends, and other key HR metrics, enabling data-driven decision-making and strategic workforce planning. By managing payroll, recruitment, and employee data through a unified platform, businesses can optimize human resource operations, reduce administrative costs, and improve employee satisfaction, all while ensuring compliance, security, and accuracy. This holistic approach to HR management ultimately enhances the overall employee experience and contributes to the long-term success of the organization.",
      buttonText: "Explore More",
    },
    {
      title: " Supply Chain",
      description: "Tracking inventory, procurement, and logistics in real time is essential for businesses to maintain operational efficiency, reduce costs, and ensure timely product availability. Real-time tracking of inventory allows companies to monitor stock levels continuously, providing accurate insights into product quantities, locations, and movement within warehouses or across multiple distribution centers. This enables businesses to prevent stockouts, reduce overstocking, and improve inventory turnover by ensuring products are replenished just in time, minimizing the need for excess storage space and working capital. The system also integrates procurement functions by automating the ordering process based on predefined inventory thresholds, supplier lead times, and demand forecasts. When stock levels reach a certain point, the system can trigger automatic purchase orders or alert procurement managers to review and approve orders, ensuring that inventory is replenished without delay. Additionally, procurement processes can be tracked for status updates, such as order confirmations, shipping statuses, and delivery dates, allowing businesses to manage supplier relationships more effectively and ensure that orders are delivered on time. Logistics tracking is equally critical as it allows businesses to monitor the movement of goods from suppliers to warehouses, distribution centers, and ultimately to customers. By utilizing GPS, RFID, and barcode scanning technologies, businesses can track shipments in real time, receiving updates on the location and estimated arrival times of goods. This visibility helps in optimizing shipping routes, minimizing delays, and improving customer satisfaction through more accurate delivery estimations. Integration with advanced analytics allows companies to forecast demand, analyze trends, and make data-driven decisions regarding procurement and inventory management. Furthermore, real-time tracking systems provide valuable insights into cost management by allowing businesses to compare supplier pricing, shipping costs, and inventory holding costs, enabling them to make more informed decisions to reduce expenses. By tracking inventory, procurement, and logistics in real time, companies gain greater control over their supply chain operations, improve accuracy, enhance responsiveness, and create a more agile, cost-effective business model that can quickly adapt to market changes and customer demands.",
      buttonText: "Get Started",
    },
    {
      title: "  CRM Integration",
      description: "Streamlining sales processes and customer relationship management (CRM) is essential for enhancing operational efficiency, improving customer satisfaction, and driving business growth. By automating various stages of the sales process, businesses can reduce manual efforts, eliminate bottlenecks, and create a seamless experience for both sales teams and customers. A streamlined sales process begins with lead generation, where automation tools can capture and qualify leads through forms, emails, or website interactions, ensuring that no potential opportunity is missed. Once leads are qualified, sales teams can be guided through predefined workflows that prioritize prospects based on factors such as potential deal size, stage in the sales funnel, and previous interactions, ensuring that resources are focused on the most promising opportunities. Integrated CRM systems enhance this by consolidating customer information into a single platform, allowing sales teams to access detailed customer profiles, interaction histories, preferences, and purchasing behaviors. This 360-degree view enables personalized engagement, allowing sales representatives to tailor their communication and approach to each individual, enhancing the likelihood of successful conversions. Automating follow-ups, reminders, and sales alerts ensures that no opportunity is left unattended, while predictive analytics can provide insights into the likelihood of closing deals, enabling sales teams to make data-driven decisions on where to focus their efforts. Additionally, CRM systems facilitate better collaboration within sales teams by allowing seamless sharing of information, tracking of sales activities, and monitoring of performance metrics. Real-time updates ensure that all team members are aligned and can quickly respond to customer needs or changes in the sales pipeline. On the customer side, streamlined processes improve satisfaction by reducing response times, offering more personalized interactions, and ensuring that customers receive timely updates and resolutions to their queries. By integrating sales automation with CRM, businesses can improve customer retention, enhance sales team productivity, and increase conversion rates, all while fostering stronger, more lasting relationships with customers. This holistic approach to sales and CRM ensures that both the operational side of the business and the customer experience are optimized, leading to increased sales, greater customer loyalty, and long-term business success.",
      buttonText: "Get Started",
    },
    {
      title: "Automation",
      description: " Reducing manual tasks and minimizing errors is crucial for enhancing productivity, efficiency, and accuracy within any business operation. By automating repetitive processes, businesses can free up valuable time and resources, allowing employees to focus on higher-value tasks that require critical thinking and creativity. Manual tasks, such as data entry, document processing, inventory management, and customer communications, are often prone to human error, which can lead to inaccuracies, delays, and additional costs. Automation eliminates these risks by applying predefined rules and algorithms to ensure that tasks are completed consistently, accurately, and on time. For example, instead of manually inputting data into systems, automation tools can gather, process, and input data automatically from various sources, reducing the likelihood of typos, miscalculations, and inconsistencies. Similarly, in areas such as inventory management, automation can track stock levels, manage reorder points, and update inventory counts in real time, reducing errors caused by manual counting and record-keeping. Automated systems also provide real-time validation and error-checking, which help ensure that the information entered into a system adheres to pre-established standards or rules, preventing errors from propagating through the workflow. Additionally, automation reduces the need for manual interventions in time-consuming tasks like payroll processing, billing, or financial reporting, ensuring that calculations are performed accurately and reports are generated on time without the risk of overlooking important details. With fewer manual interventions, businesses can also improve compliance, as automated systems can be programmed to follow regulatory requirements and industry standards, reducing the risk of non-compliance or legal issues. By reducing manual tasks and minimizing errors, businesses can achieve greater operational efficiency, cost savings, and employee satisfaction, as automation alleviates the burden of tedious, error-prone tasks. Furthermore, this leads to improved customer satisfaction, as accurate and timely services are provided, strengthening brand reputation and driving long-term success.",
      buttonText: "Get Started",
    },
    {
      title: "  Customizable",
      description: "Tailoring specific modules to fit unique business requirements is a strategic approach that ensures software solutions are fully aligned with the goals, processes, and challenges of a particular organization. Every business operates differently, with distinct workflows, priorities, and operational nuances, and off-the-shelf solutions often fail to meet these specific needs. Customizing modules allows businesses to integrate only the features they need, streamline processes, and optimize workflows for maximum efficiency and effectiveness. Whether it’s adjusting inventory management to accommodate unique product categories, modifying customer relationship management (CRM) tools to better capture and track client interactions, or adapting financial modules to reflect specific accounting practices, tailoring ensures that the software works seamlessly with the business rather than forcing the business to adapt to generic processes. This approach provides flexibility in designing user interfaces that are intuitive and specific to how employees interact with the system, ensuring ease of use and enhancing productivity. Furthermore, tailoring allows businesses to integrate third-party tools, platforms, or systems that are essential for their operations, such as payment gateways, data analytics tools, or inventory management systems, creating a comprehensive ecosystem that is customized for the organization’s needs. These custom modules can also adapt over time as the business grows or as industry regulations evolve, ensuring the solution remains scalable and relevant. By aligning technology with business requirements, organizations can improve operational efficiency, reduce the risk of errors, and enhance overall performance. Additionally, this approach helps with faster adoption of new software, as employees are more likely to embrace tools that directly address their daily tasks and challenges, leading to increased user satisfaction, reduced training time, and higher return on investment. Ultimately, tailoring specific modules to fit unique business requirements ensures that the technology investment serves the company’s unique needs, helping the business remain agile, competitive, and successful in a rapidly changing market environment.",
      buttonText: "Get Started",
    },
    
 
  ];

  return (
    <div style={{backgroundColor:"#f5f5f5",position:"relative",marginTop:"-24px" }}>
      <h2 style={{textAlign:"center", fontSize:"30px", paddingTop: 40, backgroundColor:"#f5f5f5"}}>Beelinx Products</h2>
      <p style={{textAlign:"center", fontSize:"20px", paddingBottom: 40 , paddingTop:20,backgroundColor:"#f5f5f5"}}>Innovative Financial Solutions for Seamless Integration, Efficiency, and Growth.</p>
    <section className={styles.driveEfficiencySection}>
      {/* Static Video */}
      <div className={styles.staticVideoContainer}>
        <video
          src="/Beelinx_features_demo.mp4" // Correct path to public folder
          className={styles.staticVideo}
          autoPlay
          loop
          muted
        >
          Your browser does not support the video tag.
        </video>
      </div>

      {/* Scrolling Content */}
      <div className={styles.contentContainer}>
        {content.map((item, index) => (
          <div className={styles.contentBlock} key={index}>
            <h3>{item.title}</h3>
            <p>{item.description}</p>
            <button className={styles.button}>{item.buttonText}</button>
          </div>
        ))}
      </div>
    </section>
    </div>
  );
};

export default ERPScrollSection;
