import React from "react";
import styles from "./PMSScrollSection.module.css";

const PMSScrollSection = () => {
  const content = [
    {
      title: " Multi-Channel ",
      description: "Accepting payments via credit/debit cards, UPI, net banking, mobile wallets, and QR codes provides businesses with the flexibility to cater to a wide range of customer preferences, enhance the convenience of transactions, and increase the likelihood of successful sales. Credit and debit card payments are the most common and widely accepted methods, allowing customers to pay easily using their bank-issued cards, whether physically or via contactless technology, thus providing a secure and efficient payment option. UPI (Unified Payments Interface) has rapidly become a popular and fast-growing payment method in regions like India, enabling customers to make instant payments directly from their bank accounts using mobile devices, offering a highly convenient and cost-effective alternative. Net banking, another secure payment method, allows customers to make payments directly from their bank accounts via online portals, offering a trusted, straightforward option for those who prefer to avoid third-party wallets. Mobile wallets, such as Apple Pay, Google Pay, or Paytm, provide customers with a fast and secure way to complete transactions by storing multiple payment methods digitally, allowing for quick tap-to-pay or app-based payments without the need for physical cards. Additionally, QR code payments have gained significant traction in the digital payments landscape, enabling businesses to generate unique codes that customers can scan using their smartphones to make instant payments through their preferred app or wallet. By accepting a variety of payment methods, businesses ensure that they can cater to a diverse customer base, increase the chances of securing payments, and streamline the checkout process, all while improving customer satisfaction and loyalty. Furthermore, the integration of multiple payment options into a single payment system simplifies accounting, reduces the risk of fraud, and ensures that businesses can operate smoothly across both physical and online platforms. Overall, offering multiple payment methods not only enhances the customer experience but also positions businesses for success in an increasingly digital and cashless world, allowing them to meet evolving consumer expectations and maximize revenue opportunities.",
      buttonText: "Learn More",
    },
    {
      title: "Real-Time",
      description: "Monitoring incoming payments instantly with real-time updates is a crucial practice for businesses seeking to maintain accurate financial records, improve cash flow management, and enhance overall operational efficiency. By leveraging modern payment systems that provide real-time updates, businesses can instantly track when payments are received, whether through credit/debit cards, bank transfers, mobile wallets, or other digital payment methods. This immediate visibility into incoming payments allows businesses to confirm that transactions have been processed successfully, reduce the likelihood of payment delays or errors, and ensure that their cash flow remains stable and predictable. Real-time updates also help businesses identify any issues or discrepancies, such as failed transactions, chargebacks, or fraud attempts, allowing for prompt resolution before they escalate into bigger problems. With integrated payment processing systems, businesses can automatically update their financial records as payments are received, ensuring that accounting and inventory systems are always in sync. This seamless flow of information eliminates the need for manual reconciliation, saving time and reducing the risk of errors. Additionally, real-time payment monitoring provides valuable insights into payment trends, customer behavior, and sales performance, helping businesses make informed decisions regarding pricing, promotions, and resource allocation. For customer-facing businesses, this also means that customers can receive immediate confirmation of their payments, improving the overall experience and building trust. Furthermore, real-time payment tracking can help businesses stay on top of their financial obligations, as they can instantly see which payments have been made and which are still outstanding. In an increasingly fast-paced digital economy, having access to real-time payment data empowers businesses to stay agile, respond quickly to challenges, and optimize their financial operations for greater success and profitability.",
      buttonText: "Explore More",
    },
    {
      title: " Automated Reconciliation",
      description: " Matching payments with invoices or orders automatically is a critical capability for businesses looking to streamline their accounting processes, improve accuracy, and reduce manual labor. By integrating payment processing systems with invoicing or order management systems, businesses can automate the process of matching incoming payments to the corresponding invoices or orders, ensuring that each payment is correctly accounted for without the need for manual intervention. This automation helps eliminate human errors, such as misallocating payments or missing invoice entries, which can lead to discrepancies in financial records or delays in order fulfillment. When a payment is received, the system cross-references the payment details with open invoices or outstanding orders based on factors such as amount, invoice number, customer information, and payment reference, automatically matching the payment to the correct transaction. In cases where partial payments are made, the system can allocate the payment proportionally, ensuring that the remaining balance is carried forward, and flagging any outstanding amounts for follow-up. This automated matching process also enables businesses to maintain up-to-date records of outstanding invoices, track payments more efficiently, and quickly identify any overdue or unpaid orders. Additionally, automation reduces the workload for finance teams, freeing up time for more strategic tasks, and allows businesses to improve cash flow management by ensuring that payments are recorded and applied as soon as they are received. Furthermore, by matching payments to invoices or orders automatically, businesses can enhance customer service by providing accurate payment histories and up-to-date order statuses, reducing disputes and improving communication with customers. The integration of automated payment matching not only boosts operational efficiency but also provides businesses with better insights into their financial health, helping them make data-driven decisions, optimize cash flow, and ensure timely payments and collections. Overall, automating this process supports greater accuracy, faster reconciliation, and a more streamlined approach to financial operations, ultimately driving better business outcomes.",
      buttonText: "Get Started",
    },
    {
      title: "  Payment Links",
      description: "Generating and sharing personalized payment links for quick collections is an innovative approach that simplifies the payment process for both businesses and customers, streamlining cash flow and enhancing the customer experience. By creating unique payment links for each customer, businesses can ensure that payments are securely directed to the correct account, facilitating seamless collections and reducing the risk of errors. These personalized links can be sent via email, text message, or through other communication channels, allowing customers to make payments easily from any device with just a few clicks. Whether the payment is for an invoice, subscription, or any other type of transaction, the payment link can be customized to reflect the specific amount owed, providing customers with a direct and efficient way to settle their balances. Personalized payment links can also include additional details such as due dates, order information, or promotional offers, making the payment process even more transparent and tailored to the customer’s needs. For businesses, this method reduces the need for manual follow-up and invoicing, as the payment link serves as both a reminder and an immediate payment gateway, reducing delays in collections. Furthermore, integrating these links with a secure payment gateway ensures that payments are processed swiftly and securely, supporting a variety of payment methods, including credit/debit cards, UPI, mobile wallets, or net banking. The ability to track the status of personalized payment links in real-time also provides businesses with valuable insights into collections, allowing them to monitor outstanding payments and send automated reminders or follow-ups when necessary. This approach can greatly improve cash flow, enhance customer satisfaction by offering a convenient and hassle-free payment experience, and reduce administrative costs associated with manual invoicing and payment processing. Ultimately, generating and sharing personalized payment links for quick collections helps businesses accelerate their revenue cycle, reduce outstanding receivables, and improve overall financial management, while simultaneously providing customers with a fast, easy, and secure way to complete transactions.",
      buttonText: "Get Started",
    },
    {
      title: " Recurring Payment",
      description: " Automating subscriptions or periodic payment collections is a highly efficient way for businesses to ensure consistent revenue streams, improve cash flow, and enhance the customer experience by reducing friction in the payment process. By implementing automated systems for subscription or recurring billing, businesses can set up payment schedules that align with the customer’s preferred payment frequency, such as weekly, monthly, or annually, ensuring that payments are collected on time without manual intervention. Automation eliminates the need for businesses to manually issue invoices, follow up on overdue payments, or manually process transactions, saving time and reducing administrative costs. The system can automatically charge customers’ payment methods, such as credit/debit cards, mobile wallets, or bank accounts, at the specified intervals, ensuring that payments are processed quickly and securely. In addition, automated subscriptions can be easily managed by customers, allowing them to modify their payment preferences, update payment methods, or cancel subscriptions directly through an online portal, which adds convenience and flexibility to the process. For businesses, the automation of subscription payments also provides better forecasting and financial planning, as predictable and recurring revenue can be accurately tracked and analyzed. Moreover, automated systems can send out reminders and confirmations to customers ahead of billing cycles, ensuring they are aware of upcoming payments and minimizing the risk of chargebacks or disputes. The integration of automated subscriptions with customer relationship management (CRM) systems and accounting tools ensures that payment records are seamlessly updated, providing a real-time view of revenue, customer retention, and payment statuses. This not only simplifies operations but also enhances customer satisfaction by offering a smooth, hassle-free payment experience. By automating subscription or periodic payment collections, businesses can reduce churn, increase customer loyalty, and optimize the management of recurring revenue, positioning themselves for long-term growth and financial stability.",
      buttonText: "Get Started",
    },
    {
      title: " Fraud Detection",
      description: "Identifying suspicious payment activities with AI-driven fraud detection is a critical measure for businesses seeking to protect themselves and their customers from financial loss and reputational damage caused by fraudulent transactions. AI-driven fraud detection systems leverage machine learning algorithms and advanced data analytics to analyze vast amounts of transaction data in real-time, identifying patterns and anomalies that are indicative of fraudulent behavior. By continuously learning from historical data and evolving fraud tactics, these systems can detect suspicious activities that may otherwise go unnoticed by traditional fraud detection methods. For example, the system can flag transactions that deviate from normal purchasing patterns, such as unusually large purchases, rapid multiple transactions from the same account, or payments originating from high-risk locations or devices. AI can also detect unusual behavior such as mismatched billing and shipping addresses, mismatched payment credentials, or transactions that occur outside of typical operating hours, all of which could indicate potential fraud. Additionally, AI-driven fraud detection systems can assign risk scores to each transaction, allowing businesses to prioritize which transactions to review further or investigate, enabling more efficient resource allocation. These systems can also adapt to changing fraud strategies by continuously updating algorithms based on new data, ensuring that businesses are always equipped with the latest fraud prevention measures. For customers, AI-driven fraud detection adds a layer of security by preventing unauthorized transactions and safeguarding their financial data, fostering trust in the business. Furthermore, by integrating AI-powered fraud detection with payment systems, businesses can reduce the need for manual transaction reviews, speed up the payment process, and minimize chargebacks or losses related to fraud. Ultimately, identifying suspicious payment activities through AI-driven fraud detection not only enhances the security and integrity of financial transactions but also supports a safer and more seamless payment experience for both businesses and customers, protecting both parties from the increasing threat of fraud in the digital payment landscape.",
      buttonText: "Get Started",
    },
    
 
  ];

  return (
    <div style={{backgroundColor:"#f5f5f5",position:"relative",marginTop:"-24px" }}>
      <h2 style={{textAlign:"center", fontSize:"30px", paddingTop: 40, backgroundColor:"#f5f5f5"}}>Beelinx Products</h2>
      <p style={{textAlign:"center", fontSize:"20px", paddingBottom: 40 , paddingTop:20,backgroundColor:"#f5f5f5"}}>Innovative Financial Solutions for Seamless Integration, Efficiency, and Growth.</p>
    <section className={styles.driveEfficiencySection}>
      {/* Static Video */}
      <div className={styles.staticVideoContainer}>
        <video
          src="/Beelinx_features_demo.mp4" // Correct path to public folder
          className={styles.staticVideo}
          autoPlay
          loop
          muted
        >
          Your browser does not support the video tag.
        </video>
      </div>

      {/* Scrolling Content */}
      <div className={styles.contentContainer}>
        {content.map((item, index) => (
          <div className={styles.contentBlock} key={index}>
            <h3>{item.title}</h3>
            <p>{item.description}</p>
            <button className={styles.button}>{item.buttonText}</button>
          </div>
        ))}
      </div>
    </section>
    </div>
  );
};

export default PMSScrollSection;
