import React from "react";
import styles from "./CSMSScrollSection.module.css";

const CSMSScrollSection = () => {
  const content = [
    {
      title: "Member Management",
      description: "Digital onboarding and record maintenance for members have become essential components of modern organizations, ensuring a smooth and efficient process for integrating new members and maintaining their information securely over time. The digital onboarding process streamlines the traditionally paper-heavy registration procedure, allowing new members to sign up, submit necessary documents, and provide relevant information through an online platform, saving both time and resources. This process can be customized to suit the specific needs of different organizations, whether it’s for a gym, a professional association, a membership club, or any other type of membership-based service. By using digital forms and automated workflows, the system reduces errors, ensures that all required information is collected, and allows for immediate verification of membership details. Additionally, members can upload identification, payment information, and other required documents directly through secure portals, reducing the need for manual handling of sensitive data and improving both security and accuracy. Once onboarded, the system facilitates seamless record maintenance by storing member details in a centralized, digital database that can be easily accessed, updated, and managed as needed. This ensures that member data is always up-to-date, whether it’s contact information, membership status, payment history, or preferences. Automated reminders can be set for membership renewals, updates to personal details, or upcoming events, keeping members informed and engaged without requiring manual intervention from staff. The digital system can also include features like self-service portals, where members can view and update their personal information, track membership benefits, or access exclusive content. This enhances the overall member experience by providing them with greater control over their data and interactions with the organization. Furthermore, digital record maintenance supports better reporting and analytics, allowing organizations to track membership trends, identify areas for improvement, and make data-driven decisions about future offerings or services. The automation of these processes helps free up administrative staff to focus on more valuable tasks, improving efficiency and reducing the risk of human error. In terms of security, advanced encryption methods and user authentication ensure that member data is protected from unauthorized access, while the ability to generate backups ensures that data is never lost. Ultimately, digital onboarding and record maintenance provide a modern, efficient, and secure approach to managing memberships, improving both operational workflows and member satisfaction, and ensuring that organizations can continue to engage with their members in a seamless, tech-driven manner.",
      buttonText: "Learn More",
    },
    {
      title: " Savings and Deposits",
      description: "Automating deposit collection and interest calculations is a transformative solution for financial institutions, ensuring efficiency, accuracy, and a seamless experience for both customers and the organization. By automating the deposit collection process, financial institutions can streamline the way payments are received, processed, and recorded, reducing manual intervention and minimizing the risk of errors. This automation allows for real-time updates to customer accounts, ensuring that deposits are recorded immediately and accurately, whether they are made via direct transfer, online payment systems, or physical deposits at branches. Additionally, automated systems can handle a variety of deposit types, including fixed deposits, recurring deposits, and savings account contributions, making it easier for institutions to manage large volumes of transactions without delays. The automation of interest calculations is equally critical, as it ensures that customers receive the correct interest on their deposits according to the terms of their accounts. With automated systems, interest can be calculated based on the deposit amount, interest rate, and frequency of compounding, without requiring manual input. This eliminates the chances of human error in complex calculations, and also ensures consistency and transparency, building trust with customers. Furthermore, automated systems can be programmed to update interest rates in real-time, based on market conditions or policy changes, and calculate the appropriate interest for each customer based on their specific deposit history and type of account. The system can also generate detailed reports, showing customers the breakdown of their deposit history, interest accrual, and total balance, ensuring that they have full visibility of their financial activity. By automating both deposit collection and interest calculations, financial institutions can significantly reduce operational costs, enhance customer satisfaction by providing faster and more accurate services, and improve overall efficiency in their operations. This approach also allows organizations to focus more on customer engagement and offering personalized financial products, rather than spending resources on routine manual tasks. Additionally, the integration of automated systems with online and mobile banking platforms enhances accessibility, as customers can easily make deposits and track their interest growth from anywhere, at any time. In summary, automating deposit collection and interest calculations not only simplifies financial operations but also delivers a higher level of accuracy, transparency, and convenience, benefiting both the institution and its customers in the long term.",
      buttonText: "Explore More",
    },
    {
      title: "Loan Management",
      description: "A system that handles loan application, approval, and disbursement is an essential tool for financial institutions, ensuring that the entire loan process is streamlined, efficient, and transparent for both lenders and borrowers. The loan application phase is automated through an online platform where applicants can easily submit their details, including personal information, financial status, loan amount requests, and any supporting documents. This digital system not only reduces paperwork but also speeds up the submission process, making it more accessible for a wider range of customers. The application system can be integrated with automated verification tools that instantly cross-check submitted information against various databases for identity verification, creditworthiness, and financial history, ensuring that the application process is both secure and accurate. Once the application is submitted, the approval process is automated based on pre-defined rules, such as credit score thresholds, income verification, and other criteria set by the lending institution. Automated decision-making systems can evaluate loan applications in real-time, providing instant or near-instant approvals or rejections, which drastically reduces processing time compared to traditional manual approval methods. Additionally, the system can flag high-risk applications for manual review, ensuring that potential issues are caught before they result in loan defaults. After approval, the disbursement process is automated, ensuring that loan amounts are transferred to the borrower’s account or to the designated payee, such as the educational institution, vendor, or seller. This process can be handled through various methods, including direct bank transfers, e-wallets, or checks, depending on the preferred payment method. The system also ensures that the disbursement is done in a timely manner, with automatic notifications sent to the borrower to confirm the successful transfer of funds. Throughout the entire loan process, the system provides real-time tracking for both the borrower and the lender, offering transparency into the status of the loan at every stage, from application to approval and disbursement. Furthermore, this automated system can integrate with other financial tools, such as accounting and reporting systems, making it easier for lenders to manage their loan portfolios, track disbursements, and generate necessary reports for compliance and auditing purposes. By handling loan applications, approval, and disbursement in an automated fashion, financial institutions can reduce operational costs, minimize human error, improve customer satisfaction, and increase overall efficiency, making the loan process faster, safer, and more accessible for all parties involved.",
      buttonText: "Get Started",
    },
    {
      title: "Accounting and Reporting",
      description: "Automating ledger maintenance and generating financial reports is a critical advancement in modern accounting and financial management, offering businesses and organizations a highly efficient and accurate method of managing their financial data. The automation of ledger maintenance ensures that all transactions are automatically recorded and classified in the appropriate accounts in real-time, eliminating the need for manual data entry and reducing the risk of human errors. This process involves integrating systems that track and log every financial activity, such as sales, purchases, expenses, and income, directly into the general ledger, ensuring that all records are up-to-date and accurate. Automation tools can categorize transactions according to predefined rules, such as account types or transaction categories, ensuring that they are recorded in the correct accounts without any manual intervention. This reduces the time spent on routine bookkeeping tasks and ensures that all financial data is organized, making it easier to manage large volumes of transactions and maintain accurate financial records. Furthermore, automated systems can also flag discrepancies or inconsistencies in the ledger, helping to identify potential issues early and enabling quicker resolution. When it comes to generating financial reports, automation provides a significant advantage by quickly compiling data from the ledger to create a variety of reports, such as income statements, balance sheets, cash flow statements, and profit and loss statements. These reports can be generated with a few clicks and can be customized to meet the specific needs of the organization, ensuring that stakeholders have access to the most relevant financial information at any given time. The system can be programmed to generate reports at regular intervals, such as weekly, monthly, or quarterly, and can automatically distribute them to key decision-makers and team members, ensuring that everyone is informed of the organization's financial status. Additionally, the automated system ensures that reports comply with accounting standards and regulations, providing peace of mind for businesses that need to meet legal and tax reporting requirements. By automating both ledger maintenance and financial reporting, organizations can not only improve efficiency but also enhance the accuracy and reliability of their financial data, enabling them to make more informed decisions. This also reduces the administrative burden on accounting teams, allowing them to focus on higher-value tasks such as financial analysis and strategic planning. Ultimately, automation in ledger maintenance and financial reporting provides businesses with a streamlined, efficient, and error-free approach to managing their finances, ensuring that financial data is always current, transparent, and ready for decision-making, audits, and regulatory compliance.",
      buttonText: "Get Started",
    },
    {
      title: "  App Integration",
      description: "Empowering members to access accounts, view balances, and make payments via mobile is a significant step towards enhancing convenience, accessibility, and customer satisfaction in today’s fast-paced digital world. By providing members with a mobile-friendly platform, organizations can offer a seamless, user-centric experience that allows them to manage their finances or accounts anytime, anywhere. With mobile access, members can quickly log in to their accounts, view real-time balances, check transaction histories, and track their financial activity on the go, without the need to visit physical branches or log into a desktop platform. This instant access not only saves time but also enables members to make informed decisions about their accounts based on up-to-date information. In addition, the ability to make payments via mobile adds another layer of convenience, as members can easily pay bills, transfer funds, or purchase services directly from their phones, whether using credit or debit cards, mobile wallets, or direct bank transfers. The integration of secure payment gateways ensures that all transactions are protected through encryption and multi-factor authentication, providing peace of mind for users who are concerned about the safety of their financial information. Furthermore, mobile platforms can offer features like payment reminders, push notifications, and alerts, keeping members informed about upcoming due dates, changes in account balances, or any suspicious activity. These features not only help ensure timely payments but also enhance the overall user experience by offering greater control and transparency. For organizations, mobile access also opens up opportunities to offer personalized services, such as tailored financial recommendations or promotions, based on the member's account activity. The convenience of mobile access ensures that members are more likely to stay engaged with the services provided, fostering loyalty and increasing the likelihood of recurring interactions. Additionally, mobile apps can integrate with other organizational systems, such as customer support and account management tools, providing members with quick access to help or the ability to resolve issues efficiently through live chat or automated responses. Overall, empowering members to access accounts, view balances, and make payments via mobile not only drives operational efficiency but also strengthens member satisfaction by providing them with the flexibility and control they need to manage their financial activities from the palm of their hand.",
      buttonText: "Get Started",
    },
    {
      title: "Data Analytics",
      description: "Providing insights into member trends, financial health, and growth opportunities is a powerful way for organizations to enhance decision-making, drive strategic initiatives, and offer more personalized services to their members. By leveraging advanced analytics and data-driven tools, organizations can gain a comprehensive understanding of member behavior, preferences, and financial status. Member trends, such as spending patterns, transaction histories, and engagement levels, can be analyzed to identify shifting behaviors or emerging needs, helping organizations stay ahead of the curve and adjust their offerings accordingly. This insight allows organizations to proactively address member demands, develop targeted products or services, and create tailored experiences that foster greater satisfaction and loyalty. Furthermore, analyzing the financial health of members provides organizations with a clear view of their customers’ economic well-being, allowing them to offer services such as financial planning, budgeting advice, or tailored loan products that align with individual needs. By understanding members' financial positions, organizations can also assess the risk associated with offering credit or other financial services, ensuring that decisions are based on sound data rather than assumptions. The ability to forecast growth opportunities is another key benefit of these insights. By examining historical trends and identifying patterns in member behavior, organizations can pinpoint areas with high potential for growth, whether through cross-selling, expanding service offerings, or reaching untapped markets. These data-driven insights empower organizations to make informed, strategic decisions that not only maximize revenue but also enhance member engagement and retention. In addition to providing a clearer understanding of individual members, these insights help organizations better segment their member base, allowing for more targeted marketing campaigns, promotions, and communication strategies. The use of predictive analytics further enhances this capability, enabling organizations to anticipate future trends, spot potential challenges, and adapt to changing market conditions before they impact the business. Ultimately, the ability to provide insights into member trends, financial health, and growth opportunities positions organizations to optimize their operations, improve member satisfaction, and unlock new avenues for success, creating a more competitive and sustainable business model in an increasingly data-driven world.",
      buttonText: "Get Started",
    },
    
 
  ];

  return (
    <div style={{backgroundColor:"#f5f5f5",position:"relative",marginTop:"-24px" }}>
      <h2 style={{textAlign:"center", fontSize:"30px", paddingTop: 40, backgroundColor:"#f5f5f5"}}>Beelinx Products</h2>
      <p style={{textAlign:"center", fontSize:"20px", paddingBottom: 40 , paddingTop:20,backgroundColor:"#f5f5f5"}}>Innovative Financial Solutions for Seamless Integration, Efficiency, and Growth.</p>
    <section className={styles.driveEfficiencySection}>
      {/* Static Video */}
      <div className={styles.staticVideoContainer}>
        <video
          src="/Beelinx_features_demo.mp4" // Correct path to public folder
          className={styles.staticVideo}
          autoPlay
          loop
          muted
        >
          Your browser does not support the video tag.
        </video>
      </div>

      {/* Scrolling Content */}
      <div className={styles.contentContainer}>
        {content.map((item, index) => (
          <div className={styles.contentBlock} key={index}>
            <h3>{item.title}</h3>
            <p>{item.description}</p>
            <button className={styles.button}>{item.buttonText}</button>
          </div>
        ))}
      </div>
    </section>
    </div>
  );
};

export default CSMSScrollSection;
