import React from "react";
import styles from "./LegalScrollSection.module.css";

const LegalScrollSection = () => {
  const content = [
    {
      title: "Terms Of Use",
      description: "Welcome to the Beelinx website. By accessing or using our website, you agree to comply with and be bound by the following Terms of Use. Please read these terms carefully. These Terms of Use govern your access to and use of the Beelinx website, including all content, features, and services offered on or through the website. By accessing or using the website, you acknowledge that you have read, understood, and agree to be bound by these terms and any other applicable policies or guidelines. If you do not agree to these terms, you are prohibited from using or accessing the Beelinx website. Beelinx reserves the right to modify, update, or amend these Terms of Use at any time without prior notice, and your continued use of the website after such modifications will constitute your acceptance of those changes. Therefore, we encourage you to review these terms regularly to stay informed of any updates. Beelinx also reserves the right to suspend or terminate your access to the website, at its sole discretion, without prior notice, should you fail to comply with these Terms of Use. Furthermore, you agree to use the website only for lawful purposes and in a manner that does not infringe the rights of, restrict, or inhibit the use of the website by any third party. By accessing and using Beelinx, you acknowledge and agree that your use may be subject to additional terms or conditions, depending on the specific services or features you engage with, and it is your responsibility to ensure that you fully understand those additional terms. Should you have any questions regarding these Terms of Use, please feel free to contact us at the provided contact information on the website. ",
      buttonText: "Learn More",
    },
    {
      title: "Acceptance of Terms",
      description: "By using our website, you accept these Terms of Use in full. If you disagree with any part of these terms, you must not use our website. These terms are carefully designed to ensure a safe, secure, and fair experience for all users, and by accessing or utilizing any aspect of the Beelinx website, you confirm your acceptance of all provisions outlined herein. If you do not agree with any specific part of the terms, we kindly request that you refrain from using our services or browsing the site. You acknowledge that your use of the Beelinx website is conditional on your agreement to these Terms of Use, and any action you take on the website signifies your understanding and acceptance of these terms. We also reserve the right to modify or update these Terms of Use as necessary. Modifications: Beelinx reserves the right to modify, alter, or amend these Terms of Use at any time, and without prior notice. Any changes made to these terms will be promptly posted on this page, and you are responsible for reviewing the Terms of Use regularly to stay informed about any changes. Your continued use of the Beelinx website after any modifications signify your acceptance of the updated terms and conditions. Should you continue to access and use the Beelinx website, you will be deemed to have accepted the modified terms, and they will govern your use of the website. Beelinx reserves the right to make modifications at its discretion, and by using the website, you agree to comply with all such changes upon their publication. It is your responsibility to regularly check for updates to the Terms of Use and to ensure that you fully understand the changes made.",
      buttonText: "Learn More",
    },
    {
      title: "License to Use Website",
      description: " Unless otherwise stated, Beelinx and/or its licensors own the intellectual property rights in the website and all the materials available on the website. This includes, but is not limited to, the text, images, videos, logos, trademarks, graphics, software, and any other content displayed or available through the website. All such content is protected by copyright, trademark, and other intellectual property laws, and your use of these materials is strictly governed by the terms outlined in these Terms of Use. You are granted a limited, non-exclusive, non-transferable license to access, view, download, and print materials from the Beelinx website for personal, non-commercial use only, provided that you comply with the restrictions specified herein. The license you receive does not grant you the right to modify, distribute, reproduce, or commercially exploit any content from the website in any manner. You must not republish, sell, rent, lease, or sub-license any material from the Beelinx website. You are also prohibited from reproducing, duplicating, copying, or otherwise exploiting any material on the website for commercial purposes or personal gain. Editing or altering any material on the website in any way, including but not limited to modifying text, images, videos, or other content, is also forbidden. Additionally, redistributing any material from the website, whether for commercial or non-commercial purposes, without explicit permission from Beelinx is not allowed. Any unauthorized use of the materials found on the Beelinx website may result in the immediate termination of your right to access and use the website, and Beelinx reserves the right to pursue legal action to protect its intellectual property rights.",
      buttonText: "Learn More",
    },
    {
      title: "User Conduct",
      description: "Prohibited Conduct: Users must not use the Beelinx website in any way that causes, or may cause, damage to the website or impairment of its availability, performance, or accessibility. This includes any actions that interfere with the normal operation of the website, disrupt or degrade its functionality, or introduce vulnerabilities that could potentially harm the website or its users. Users are prohibited from using the website to engage in activities that could compromise the security or integrity of Beelinx’s infrastructure, such as introducing harmful code, including viruses, worms, malware, or other malicious software that may cause damage to the website or other users’ devices. Any attempt to gain unauthorized access to the Beelinx website, systems, or networks, or to exploit any security vulnerabilities, is strictly prohibited. Furthermore, users must not use the Beelinx website in any manner that is unlawful, fraudulent, or harmful to others. This includes, but is not limited to, engaging in any conduct that violates applicable local, national, or international laws, regulations, or third-party rights, including intellectual property rights. Users must not engage in fraudulent activities, such as impersonating others, misrepresenting themselves, or attempting to deceive or manipulate other users or the website’s systems. Any use of the website to promote or distribute harmful, abusive, harassing, defamatory, or offensive content is strictly prohibited, as is any activity that could harm Beelinx’s reputation, its users, or the trust that others have placed in the website. Additionally, users should refrain from using the Beelinx website in a way that could harm the safety or security of its infrastructure or other users, including any activities that could compromise the personal information of others or create an unsafe online environment. This includes actions such as spamming, sending unsolicited communications, or engaging in conduct that may result in a negative experience for other users. Beelinx reserves the right to monitor user activity and take any necessary actions, including blocking, restricting, or suspending access to the website, to ensure that these terms are upheld. Any violations of this policy may result in immediate termination of access to the website, legal action, and potential claims for damages. Beelinx is committed to protecting the interests of its users, ensuring a safe online environment, and safeguarding its website from any form of abuse or malicious activity.",
      buttonText: "Learn More",
    },
    {
      title: "Disclaimer of Warranties",
      description: " The Beelinx website is provided on an 'as is' basis, without any representations or warranties, whether express or implied, regarding its accuracy, completeness, availability, or suitability for any particular purpose. Beelinx does not make any representations or warranties in relation to the website or the information and materials provided on the website, including, but not limited to, the content, functionality, or features of the website. Beelinx does not guarantee that the website will be free from errors, interruptions, or viruses, or that it will meet your specific requirements or expectations. Additionally, Beelinx makes no warranty regarding the quality, reliability, or performance of any content or services accessed through the website. Users acknowledge that any reliance on the information or materials provided on the website is done at their own risk, and Beelinx shall not be held liable for any loss, damage, or inconvenience arising from the use of the website or any reliance on its content. Beelinx specifically disclaims all implied warranties, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, and non-infringement. Beelinx also does not warrant that the website or its servers are free from harmful components such as malware or viruses, and it is the responsibility of users to take appropriate precautions to ensure that their devices are adequately protected. Furthermore, Beelinx does not make any representations regarding the accuracy, timeliness, or completeness of the content on the website, nor does it guarantee that the website will be available or operational at all times. Any changes to the website, its functionality, or its content may be made at the sole discretion of Beelinx, and users are encouraged to regularly review these terms for any updates or modifications.",
      buttonText: "Learn More",
    },
    {
      title: "Exclusion of Liability",
      description: "Beelinx will not be held liable to you in relation to the contents of, or your use of, or otherwise in connection with, this website for any indirect, special, incidental, or consequential losses, damages, or expenses. This includes, but is not limited to, any loss of profits, loss of revenue, loss of income, loss of anticipated savings, or loss of business opportunities arising from your access to or use of the website. Beelinx shall not be responsible for any damages resulting from the interruption, suspension, or termination of the website, whether caused by technical issues, system failures, or any other reason. Additionally, Beelinx is not liable for any damages that may occur as a result of your reliance on the information, content, or materials provided on the website, including any inaccuracies or omissions. You acknowledge and agree that Beelinx shall not be responsible for any financial or operational losses you may incur, nor for any indirect or consequential damages, even if Beelinx has been advised of the possibility of such losses. This exclusion of liability applies to all situations, including those involving the use of third-party services, links, or content accessed through the Beelinx website. Users assume full responsibility for their use of the website and agree that Beelinx shall not be liable for any claims, damages, or losses that may arise from such use, including but not limited to personal injury, financial loss, or any loss related to the use of content or services provided through the website.",
      buttonText: "Learn More",
    },
    {
      title: "Governing Law-Jurisdiction",
      description: "These Terms of Use will be governed by and construed in accordance with the laws of [Your Country/State], without regard to its conflict of law principles. By accessing or using the Beelinx website, you agree that any dispute, claim, or controversy arising out of or in connection with these terms, the website, or any services provided through the website, will be subject to the exclusive jurisdiction of the courts of [Your Country/State]. This includes any claims related to the interpretation, enforcement, or breach of these Terms of Use, and any disputes concerning the performance or non-performance of Beelinx in relation to your use of the website. You further consent to the exclusive venue of the courts located in [Your Country/State], and waive any objection to such jurisdiction or venue, including any claims of inconvenience or improper venue. In the event of a dispute, Beelinx may, at its sole discretion, choose to resolve the matter through alternative dispute resolution mechanisms such as arbitration or mediation, in accordance with the rules and procedures applicable in [Your Country/State]. However, nothing in these terms limits Beelinx's right to seek injunctive or equitable relief in any jurisdiction, if necessary, to protect its intellectual property or prevent harm to its website or users. By continuing to use the Beelinx website, you acknowledge and accept that any legal action, litigation, or dispute related to these terms will be handled exclusively in accordance with the laws and courts of [Your Country/State], and agree to submit to the jurisdiction of those courts.",
      buttonText: "Learn More",
    },
    {
      title: "Contact Us",
      description: "If you have any questions, concerns, or require further clarification regarding these Terms of Use, we encourage you to reach out to us. We are committed to ensuring that you fully understand the terms and conditions that govern your use of the Beelinx website and that your experience with our services is as smooth and informed as possible. For any inquiries or feedback, you can contact us via email at [legal@beelinx.com], where our dedicated legal and support teams are available to assist you with detailed responses to your questions. Should you prefer to discuss matters directly or if you require immediate assistance, feel free to contact us by phone at [Phone Number]. Our team will be happy to provide the support you need and address any issues you may encounter during your use of the website or services. If you prefer to communicate with us via traditional mail or if you wish to visit us in person for a more in-depth discussion, you can send correspondence or visit our physical office at [Physical Address]. Our doors are always open to help you navigate any concerns regarding the Terms of Use, our policies, or the functionality of the website. Whether you have questions about specific clauses, need assistance with account issues, or wish to discuss any legal matters related to the website, we are here to provide clear guidance and effective solutions. Your understanding of our terms and your satisfaction with our services are of the utmost importance to us, so please do not hesitate to reach out through any of these contact methods for assistance.",
      buttonText: "Learn More",
    },
    {
      title: "Privacy Policy",
      description: " Introduction: Beelinx is deeply committed to protecting the privacy, confidentiality, and security of your personal information. We recognize the importance of safeguarding your data and ensuring that it is treated with the utmost care. This Privacy Policy explains in detail how we collect, use, disclose, store, and protect the personal information we gather from users ('you' or 'your') of our website, mobile application, SAAS platform, and all other services we provide (collectively referred to as the 'Services'). We understand that your trust is essential, and as such, we are dedicated to being transparent about how your personal data is handled and to providing you with control over your information. This policy describes the specific types of information we collect, the purposes for which we use it, the third parties with whom we may share it, and the robust security measures we employ to ensure its safety. Additionally, it outlines your rights concerning your personal data, including how you can access, update, or delete the information we hold. By accessing or using our Services, you consent to the collection, use, and disclosure of your information as described in this Privacy Policy. Beelinx takes every possible measure to ensure that your data is handled responsibly and securely throughout your experience with our Services, and we are committed to maintaining transparency regarding any changes to our privacy practices. We encourage you to review this Privacy Policy regularly to stay informed about how we protect your personal information.",
      buttonText: "Learn More",
    },
    {
      title: "Information We Collect",
      description: "Types of Information: Beelinx may collect various types of personal information from you to provide and improve our Services, ensure seamless user experiences, and comply with legal requirements. The information we collect can include, but is not limited to, the following: Account Information: When you create an account with Beelinx, we may collect personal details such as your name, email address, phone number, and other relevant contact information necessary for account management and communication. Financial Information: In order to facilitate transactions, process payments, and provide our financial services, we may collect sensitive financial information, such as your bank account details, credit card information, or other payment methods that you provide to complete a purchase or engage in financial transactions with Beelinx. Usage Data: Beelinx also collects information regarding how you interact with our Services. This may include your browsing activity, device information, operating system, IP address, location data, and other information related to the use of our website, mobile application, or SAAS platform. This data helps us understand user behavior, improve our services, troubleshoot technical issues, and enhance user experience. Communications: When you reach out to us for support, inquiries, or other communication purposes, we may collect details about your interactions, such as your messages, the nature of your inquiry, and any other information you share with our customer support team. This allows us to respond appropriately to your requests, provide efficient customer support, and maintain a high level of service. We take the protection of all personal information seriously and handle it in accordance with this Privacy Policy, ensuring that it is used solely for the purposes outlined herein and with the highest level of confidentiality.",
      buttonText: "Learn More",
    },
    {
      title: "Your Choices and Rights",
      description: "Rights: You have certain rights regarding the personal information that Beelinx collects and processes about you. These rights are designed to give you control over how your data is handled and to ensure that your privacy is protected. You have the right to access the personal information we hold about you, allowing you to review and verify its accuracy. If you find that your information is inaccurate, incomplete, or outdated, you have the right to update or correct it to ensure that it remains accurate and up-to-date. You also have the right to request the deletion of your personal information, subject to any legal obligations we may have to retain certain data. In addition, you may have the right to object to certain processing activities, particularly if the processing is based on legitimate interests or consent, and to request that we limit or restrict the use of your personal information in specific circumstances, such as when you believe the data is inaccurate, the processing is unlawful, or you no longer wish for us to use your data for particular purposes. To exercise any of these rights, or if you have any questions or concerns about the handling of your personal information, please contact us using the contact details provided below. We will respond to your request in a timely manner and ensure that your rights are respected in accordance with applicable data protection laws and regulations. Beelinx is committed to making the process as straightforward as possible for you, and we will work with you to address any issues or requests you may have concerning your personal information.",
      buttonText: "Learn More",
    },
    {
      title: "Data Security",
      description: " Security Measures: At Beelinx, we take your privacy and the security of your personal information very seriously. We implement a variety of reasonable technical, physical, and administrative measures designed to safeguard the confidentiality, integrity, and availability of your personal data. These measures include encryption, secure server technologies, access control systems, firewalls, and regular security audits to prevent unauthorized access, alteration, or destruction of your information. Our team is committed to employing industry-standard practices to protect your personal data from potential threats, whether accidental or malicious, and to maintain a secure environment for the services we provide. However, despite our best efforts and the implementation of robust security systems, it is important to recognize that no security protocol or technology can be guaranteed to be entirely foolproof. While we take all reasonable steps to secure your information, the nature of the internet and digital technologies means that risks remain, and we cannot guarantee the absolute security of your personal data. We encourage you to take appropriate precautions when interacting with our Services, such as using strong, unique passwords and maintaining up-to-date security software on your devices. By using Beelinx’s Services, you acknowledge and accept that, while we strive to protect your personal information to the best of our ability, there may still be some inherent security risks, and we cannot provide an absolute guarantee of complete security. Nonetheless, Beelinx remains dedicated to continuously improving and updating our security measures in response to emerging risks and challenges.",
      buttonText: "Learn More",
    },
    {
      title: "Updates to this Privacy Policy",
      description: "Policy Changes: Beelinx reserves the right to update or modify this Privacy Policy periodically to reflect changes in our data practices, business operations, or in response to new legal, regulatory, or technological developments. As part of our commitment to transparency and to keeping you informed, we will notify you of any significant changes to the policy by posting the updated version on our website. In some cases, we may also notify you through other appropriate communication channels, such as email or direct notifications within our Services, to ensure that you are aware of any material modifications. It is important that you regularly review the Privacy Policy to stay informed about how we collect, use, and protect your personal information. Any updates to this policy will be effective as soon as they are posted, unless a later date is specified, in which case the changes will be effective as of that date. By continuing to use our Services after the updated Privacy Policy has been posted, you acknowledge and agree to the changes. If you do not agree with the updated policy, we encourage you to discontinue use of the Beelinx Services and contact us with any concerns regarding your personal information. Beelinx is committed to maintaining the highest standards of privacy and security, and we strive to ensure that our policies are always aligned with your rights and expectations.",
      buttonText: "Learn More",
    },
    {
      title: "Contact Us",
      description: "Contact Information: If you have any questions, concerns, or require additional information regarding this Privacy Policy, our data practices, or any aspect of how we handle your personal information, we encourage you to reach out to us. Beelinx places great importance on transparency and the protection of your privacy, and we are fully committed to addressing any inquiries or issues you may have. Should you have any doubts or need clarification about the way we collect, use, or store your data, or if you wish to exercise any of your privacy rights, please feel free to contact us. You can easily reach us by sending an email to [privacypolicy@beelinx.com], and our team will make it a priority to provide a comprehensive response to your inquiry as quickly as possible. Whether you need detailed explanations of specific terms in this policy or have concerns about how your information is being managed, we are here to assist you. If you prefer a more direct conversation or need urgent assistance, you are welcome to contact us by phone at [Phone Number], where our dedicated customer support representatives will be available to address your concerns. For those who wish to engage with us in person or send formal written communication, our physical office is located at [Physical Address], and we welcome any correspondence that helps us ensure your privacy rights are respected. We take great pride in offering responsive customer support and are committed to resolving any privacy-related issues promptly and efficiently. Whether you need help with data access requests, clarification on how we use your information, or have concerns about the security of your personal data, we are ready and available to support you. Your privacy is paramount to us at Beelinx, and we want to ensure that you feel confident and well-informed when using our Services. Please do not hesitate to contact us through any of the methods provided, and we will make every effort to assist you with your concerns in a clear and timely manner.",
      buttonText: "Learn More",
    },
    
    {
      title: "Compliance",
      description: "Introduction: At Beelinx, we recognize that trust and transparency are fundamental in any business relationship, especially in the digital and financial services industry. We understand that the security and privacy of your personal information are paramount, and as such, we are dedicated to upholding the highest standards of compliance with industry regulations and best practices. Our commitment to ensuring the safety of your data, the integrity of our services, and your overall satisfaction is central to everything we do. Beelinx strives to maintain clear, open communication with our customers and adheres to a strict framework of security protocols and compliance measures to protect your interests. Whether you are using our website, mobile application, or SAAS platform, our primary focus is to create an environment where you feel confident and secure while engaging with our services. We continuously review and update our policies and systems to adapt to evolving regulatory requirements and to maintain the highest level of trust with our customers. Our goal is not just to meet compliance standards, but to exceed your expectations by delivering reliable, secure, and transparent services that you can trust. At Beelinx, your satisfaction is our top priority, and we are fully committed to fostering a long-term relationship built on mutual trust and respect.",
      buttonText: "Learn More",
    },
    {
      title: "Regulatory Compliance",
      description: "Compliance Standards: Beelinx operates in full accordance with all relevant regulations, laws, and guidelines set forth by regulatory bodies such as the Reserve Bank of India (RBI), the National Payments Corporation of India (NPCI), banks, the Payment Card Industry Data Security Standard (PCI DSS), the Financial Intelligence Unit (FIU), and other governing authorities that oversee the financial services and digital payment industries. Our compliance team plays a crucial role in ensuring that our operations are constantly aligned with the latest legal requirements and regulatory standards. We take a proactive approach in monitoring regulatory developments and any changes in the legal landscape that may impact our services. This ensures that Beelinx consistently operates within the boundaries of the law and remains fully compliant with all applicable rules. Our commitment to compliance extends to every aspect of our business operations, from data security and customer privacy to payment processing and reporting practices. We rigorously evaluate and update our policies, systems, and practices to ensure that we meet or exceed industry standards for security, transparency, and accountability. By adhering to these stringent compliance frameworks, Beelinx aims to provide a safe, secure, and trustworthy environment for our customers, while also ensuring that our business operates ethically and responsibly. As part of our ongoing commitment, we regularly conduct internal audits, engage with external compliance experts, and maintain an open dialogue with regulatory bodies to ensure that our practices remain up to date and in full compliance with evolving standards.",
      buttonText: "Learn More",
    },
    {
      title: "Customer Protection",
      description: "At Beelinx, the security and privacy of our customers' financial information are our top priorities, and we recognize the immense responsibility that comes with handling such sensitive data. To ensure your information is protected against unauthorized access, fraud, and data breaches, we employ cutting-edge security measures that are continuously updated to meet the highest industry standards. This includes robust encryption protocols to secure data during both transmission and storage, multi-factor authentication (MFA) to provide an additional layer of protection against unauthorized access, and regular, thorough security audits to identify potential vulnerabilities and take proactive steps to address them. Our dedicated security team works tirelessly, 24/7, to monitor all systems and swiftly respond to any suspicious activity, ensuring that your data is always secure. In addition to these advanced technical safeguards, Beelinx is committed to maintaining transparency with our customers. We believe that clear, honest communication is essential, especially when it comes to matters of security. Should any security issues or concerns arise, we notify our customers promptly, providing detailed information and offering guidance on the steps we are taking to resolve the situation. We also prioritize quick resolution of any security-related matters, ensuring that you are kept informed throughout the process. By combining cutting-edge security practices with a commitment to transparency and customer protection, Beelinx strives to provide a safe and trustworthy environment, ensuring that you can use our services with complete confidence in the protection of your financial data.",
      buttonText: "Learn More",
    },
    {
      title: "Privacy Policy",
      description: "Policy Overview: At Beelinx, we are fully committed to protecting your privacy and safeguarding your personal information. Our Privacy Policy outlines in detail how we collect, use, store, and protect your data, ensuring that your privacy rights are respected at all times. We understand the importance of transparency and strive to comply with all applicable data protection laws and regulations to give you full confidence in how your information is handled. Our Privacy Policy is designed to be clear, easy to understand, and readily accessible on our website, ensuring that you can always review it at any time. The policy provides comprehensive information on the types of data we collect, including personal and financial information, how we use this data to provide and improve our services, and the various rights you have regarding your information, including your rights to access, correct, or delete it. By clearly outlining how your data is collected and used, we aim to build a strong foundation of trust with you, and to ensure that you are informed and in control of your personal data. At Beelinx, we take privacy seriously, and we work diligently to protect your information in accordance with industry standards and legal requirements.",
      buttonText: "Learn More",
    },{
      title: "Risk Disclosure",
      description: " Investment Risks: Investing in financial markets involves inherent risks that cannot be eliminated, and it is important for investors to recognize that past performance is not necessarily indicative of future results. At Beelinx, we believe that understanding these risks is crucial before engaging in any investment activities. Our Risk Disclosure Statement provides a comprehensive explanation of the various risks associated with investing through our platform, including but not limited to market volatility, fluctuations in asset values, economic changes, interest rate shifts, and liquidity risks, all of which can impact the performance of investments. It is essential for our customers to be aware that, while investments have the potential to generate returns, they also carry the risk of financial loss. Therefore, we strongly encourage our customers to carefully review this statement and consider their individual financial goals, risk tolerance, and investment horizon before making any decisions. We aim to provide a transparent and informative environment where customers are equipped with the knowledge necessary to understand the risks involved and make informed choices. Beelinx is dedicated to ensuring that all our customers are aware of the potential risks, empowering them to take appropriate steps to manage their investments responsibly. We also recommend that our customers seek independent financial advice if necessary, to ensure they are making well-calculated investment decisions in line with their personal financial situations. By providing clear and accessible information on these risks, we strive to help our customers navigate the complexities of the financial markets with greater confidence and understanding.",
      buttonText: "Learn More",
    },{
      title: "Anti-Money Laundering (AML) Policy",
      description: "AML Commitment: At Beelinx, we are deeply committed to preventing our platform from being used for illicit activities, including money laundering and the financing of terrorism. As part of our dedication to maintaining the integrity of our services and protecting the financial ecosystem, we have implemented a comprehensive Anti-Money Laundering (AML) Policy. This policy includes rigorous customer identification procedures designed to verify the identities of all users before they engage in any financial transactions, ensuring that we only serve legitimate customers. In addition, we employ advanced transaction monitoring systems that continuously analyze user activity for any signs of suspicious behavior or transactions that may indicate money laundering or other illegal activities. If any potentially suspicious activities are detected, we take immediate action by reporting these activities to the relevant regulatory authorities in accordance with local and international legal requirements. Beelinx works diligently to ensure full compliance with AML laws and regulations to prevent our services from being exploited for criminal purposes. By adhering to stringent AML standards, we not only protect the integrity of our platform and the financial system but also contribute to the global fight against financial crime. Our commitment to AML practices helps create a secure and trustworthy environment for all our customers, and we continue to invest in the latest technologies and best practices to stay ahead of emerging threats.",
      buttonText: "Learn More",
    },
    {
      title: "Customer Support",
      description: "Support Services: At Beelinx, we are committed to providing exceptional customer support to ensure that your experience with our platform is as seamless, secure, and worry-free as possible. We understand that, from time to time, you may have questions or concerns about our compliance practices, policies, or any other aspect of our services. That’s why we’ve made our Customer Support team readily available to assist you with any inquiries, providing you with clear, timely, and thorough responses. Whether you need clarification on how your data is protected, need assistance understanding our terms of service, or have questions regarding the security of your transactions, our team is here to help. We take great pride in offering not just reactive support, but proactive guidance to help you navigate our platform with confidence. Our dedicated support staff is highly trained to handle a wide range of issues, and we are fully committed to resolving any concerns you may have quickly and effectively. We believe in maintaining transparency and building trust with our customers, which is why we ensure that all of your queries, whether they are related to our privacy policies, security measures, or compliance standards, are answered thoroughly and to your satisfaction. At Beelinx, we view customer support as an ongoing relationship, not just a one-time interaction, and we strive to ensure that you feel supported every step of the way. Whether you're looking for assistance with a technical issue, need help understanding complex regulatory policies, or simply want more information about how we operate, our team is always ready and eager to provide the assistance you need. We believe that a well-informed customer is a confident customer, and we work tirelessly to ensure that your questions are addressed promptly and with the highest level of professionalism. Your peace of mind and trust in our services are paramount to us, and we are dedicated to giving you the best support possible at every stage of your journey with Beelinx.",
      buttonText: "Learn More",
    },
    {
      title: "Stay Informed",
      description: "Updates and News: At Beelinx, we recognize that staying informed is crucial in today’s fast-paced financial landscape, especially as regulatory changes, technological advancements, and industry developments can significantly influence the way you manage your finances and make investment decisions. As part of our commitment to transparency and customer empowerment, we make it a priority to keep our customers updated on all relevant news, regulatory updates, and changes that could impact their financial activities. We understand that navigating the world of fintech requires timely information, and we strive to provide you with the latest insights and updates to help you make informed decisions. To ensure that you never miss out on important information, we invite you to subscribe to our newsletter, where we deliver in-depth updates on the latest developments in the fintech industry, changes in financial regulations, as well as new features or improvements to our platform that could benefit you. By subscribing, you'll receive direct access to a wealth of information tailored to your interests and needs, helping you stay ahead of any changes that may affect your financial strategies. Furthermore, by following us on our social media platforms, you’ll receive real-time updates and news notifications, keeping you in the loop on breaking news, regulatory announcements, new fintech trends, and any changes that could shape the future of finance. We believe that an informed customer is a confident customer, which is why we are dedicated to providing you with all the necessary tools and information to navigate the complex world of finance and investment with confidence. Whether it’s changes to financial regulations, emerging technologies, or new compliance measures, Beelinx is here to ensure that you have access to the latest developments that matter most to your financial success. By staying connected with us through our newsletter and social media, you will always be well-equipped to make strategic decisions and adjust to any changes in the industry.",
      buttonText: "Learn More",
    },
    {
      title: "Contact Us",
      description: "Contact Information: At Beelinx, we understand the importance of maintaining clear and open communication with our customers, especially when it comes to our compliance policies and practices. If you have any questions, concerns, or require further clarification regarding our compliance measures, policies, or how we ensure the security and privacy of your personal and financial information, we are here to assist you. Our dedicated support team is always ready to provide you with detailed answers and help you understand our policies and procedures. You can reach us by email at compliance@beelinx.com, where our team will respond to your inquiries as quickly as possible. Additionally, if you prefer to speak with us directly, you can contact us by phone at [Phone Number], and one of our compliance experts will be happy to assist you. For those who may need to communicate with us in person or send physical documentation, our office address is [Physical Address], where we ensure a professional and helpful team is available to address any concerns. We take your questions seriously and are committed to providing clear, transparent information to help you feel confident in your interactions with Beelinx. Whether it's inquiries about compliance with data protection laws, security protocols, or regulatory standards, we're here to offer the support you need to ensure a smooth and informed experience.",
      buttonText: "Learn More",
    },
    
  ];

  return (
    <div>
    <div style={{backgroundColor:"#f5f5f5",position:"relative",marginTop:"-24px" }}>
      <h2 style={{textAlign:"center", fontSize:"40px", paddingTop: 40, backgroundColor:"#f5f5f5"}}>Legal Entities</h2>
      <p style={{textAlign:"center", fontSize:"20px", paddingBottom: 40 , paddingTop:20,backgroundColor:"#f5f5f5"}}>Below are our Legal Entities and related entities.</p>
    <section className={styles.driveEfficiencySection}>
      {/* Static Video */}
     

      {/* Scrolling Content */}
      <div className={styles.contentContainer}>
        {content.map((item, index) => (
          <div className={styles.contentBlock} key={index}>
            <h3>{item.title}</h3>
            <p>{item.description}</p>
            <button  className={styles.button}>{item.buttonText}</button>
          </div>
        ))}
      </div>
    </section>
    </div>
    <div className="confidence-footer">
    <p style={{ fontSize: "40px", paddingBottom: "40px" }}>
      Trusted by 20,000+ organizations worldwide
    </p>
    <div className="logos">
      <img src="brand1Beelinx.svg" alt="ABB" />
      <img src="brand2Beelinx.svg" alt="AVEVA" />
      <img src="brand3Beelinx.svg" alt="Lyft" />
      <img src="brand4Beelinx.svg" alt="Siemens" />
      <img src="brand5Beelinx.svg" alt="Schneider Electric" />
      <img src="brand6Beelinx.svg" alt="Ogilvy" />
      <img src="brand7Beelinx.svg" alt="T-Mobile" />
    </div>
  </div>
    </div>
  );
};

export default LegalScrollSection;
