import React from "react";
import styles from "./HMSScrollSection.module.css";

const HMSScrollSection = () => {
  const content = [
    {
      title: "Patient Management",
      description: "Simplified patient registration and digital record storage are transformative steps toward improving healthcare efficiency, reducing administrative burdens, and enhancing the overall patient experience. By automating the patient registration process, healthcare providers can streamline the collection of patient information, such as personal details, medical history, insurance data, and emergency contacts, through user-friendly online forms or kiosks. This eliminates the need for paper forms and manual data entry, reducing human errors and minimizing time spent on administrative tasks. Patients can quickly complete their registration at their convenience, either before arriving at the facility or upon check-in, reducing wait times and enhancing operational flow. Once registered, patient records are securely stored in digital format, making it easier for healthcare providers to access, update, and manage patient information. Digital record storage ensures that all medical data, including diagnostic results, treatment plans, medication lists, and previous consultations, are organized in one central, easily retrievable location. This not only improves the speed and accuracy of patient care but also ensures compliance with healthcare regulations, such as data privacy laws, by providing encrypted storage and secure access controls. Furthermore, digital records enable seamless sharing of patient information between healthcare providers, promoting better collaboration and coordination of care, particularly in cases where a patient seeks treatment from multiple specialists or healthcare facilities. With digital records, healthcare providers can track patient progress over time, monitor treatment outcomes, and make more informed decisions based on comprehensive patient histories. The ability to quickly update and retrieve patient information reduces administrative overhead, minimizes paperwork, and frees up time for healthcare professionals to focus more on patient care. Additionally, with simplified patient registration and digital record storage, healthcare organizations can improve patient satisfaction, increase operational efficiency, and reduce costs associated with paper-based systems, making it a win-win solution for both providers and patients. This modern approach enhances the healthcare experience, ensuring that patient care is faster, more accurate, and more connected than ever before.",
      buttonText: "Learn More",
    },
    {
      title: "Clinical Management",
      description: "Lab and diagnostic integration with automated test results is a vital advancement in modern healthcare that significantly enhances the speed, accuracy, and efficiency of medical testing and patient care. By integrating laboratory systems with healthcare platforms, patient test results are automatically transmitted from labs to the patient's digital health record, eliminating the need for manual data entry and reducing the risk of errors or delays. This seamless connection ensures that healthcare providers have real-time access to test results, enabling faster decision-making and reducing the time patients must wait for results, which can be critical in time-sensitive situations. Automated test result integration also minimizes the potential for human error, as results are directly uploaded from diagnostic instruments into the electronic health record (EHR) or laboratory information management system (LIMS), ensuring the data is accurate and up to date. This integration allows healthcare providers to efficiently manage patient testing by tracking the status of tests, identifying any pending or incomplete results, and notifying relevant staff when action is required, thus streamlining workflow and improving overall operational efficiency. In addition, with the automation of test result uploads, the process becomes more consistent, eliminating the need for manually transferring information between different systems, which can often lead to inconsistencies or mistakes. Automated alerts can be set up for abnormal test results, ensuring that healthcare professionals are promptly notified of critical values or urgent cases, which improves response times and patient outcomes. Furthermore, integrated lab and diagnostic results allow for a more holistic view of the patient’s health, as physicians can easily access historical test results, compare trends, and make better-informed decisions based on comprehensive data. With integrated and automated test result systems, healthcare organizations can improve patient care, reduce administrative burdens, enhance collaboration across departments, and ensure regulatory compliance with health data standards. This integration ultimately leads to faster diagnoses, more accurate treatments, and a more connected and efficient healthcare environment, benefiting both providers and patients.",
      buttonText: "Explore More",
    },
    {
      title: " Financial Tools",
      description: "Streamlined billing, invoicing, and insurance claim management are essential components of an efficient healthcare or business operation, ensuring that financial processes are smooth, accurate, and timely, while also improving cash flow and reducing administrative burdens. With automated billing systems, healthcare providers or businesses can generate invoices directly from patient visits or transactions, ensuring that charges are accurate and aligned with services rendered. This automation eliminates the need for manual data entry and significantly reduces the risk of billing errors, which can lead to disputes, delays, or underpayment. Streamlined invoicing ensures that customers or patients receive clear, itemized statements that reflect the charges for their services, making it easier for them to understand and process their payments. The system can also generate recurring invoices for services that require regular payments, such as subscriptions or ongoing treatments, ensuring that billing is consistent and timely. Insurance claim management becomes far more efficient through integration with electronic health records (EHR) or accounting systems, as claim forms are automatically populated with patient and treatment information, reducing the time and effort required to manually enter data. This integration ensures that insurance claims are submitted accurately, reducing the chance of claims being rejected due to incomplete or incorrect information. Automated systems can also track the status of claims in real time, providing updates on approvals, denials, or requests for additional information, and alerting staff when follow-up is necessary. This improves the speed of reimbursement and reduces delays in receiving payments. Additionally, automated billing and claim management systems can incorporate advanced features such as insurance verification, real-time claim submission, and compliance with industry regulations, which ensures that claims adhere to coding standards and billing rules, reducing the likelihood of audit issues. By streamlining these processes, healthcare providers or businesses can focus more on delivering services and improving customer satisfaction rather than spending valuable time on administrative tasks. Ultimately, this integration leads to improved revenue cycle management, faster payments, and enhanced financial performance, while also improving patient or customer experience by making billing and claims processes more transparent, accurate, and efficient.",
      buttonText: "Get Started",
    },
    {
      title: " Pharmacy Management",
      description: "Inventory tracking for medicines and supplies is a crucial aspect of healthcare operations, ensuring that essential products are available when needed while minimizing waste, shortages, and overstocking. By implementing real-time inventory tracking systems, healthcare providers can monitor the quantities of medicines and medical supplies at any given time, allowing for precise control over stock levels across various departments or storage locations. This level of visibility helps prevent stockouts, which can be critical for patient care, as it ensures that medications and supplies are always on hand and ready for use. Automated systems can also generate alerts when inventory reaches predefined thresholds, triggering reorder requests or prompting procurement managers to take action before supplies run low. Furthermore, by integrating inventory tracking with purchase order systems, healthcare organizations can automate the replenishment process, streamlining procurement and reducing the administrative burden of manual inventory checks and ordering. Barcode or RFID technologies can be used to track medicines and supplies, providing accurate and efficient tracking of products from receipt through usage, which helps maintain detailed records of stock movements and usage patterns. This level of tracking is particularly valuable in the healthcare sector, where managing expiration dates, controlled substances, and batch numbers is critical for both safety and compliance. Inventory tracking systems also support better inventory management by providing data on usage trends, enabling healthcare providers to forecast demand more accurately, plan for seasonal fluctuations, and optimize their purchasing strategies. Additionally, with digital inventory records, organizations can ensure compliance with regulations and standards for the storage and handling of medical supplies, while also reducing the risk of theft, misplacement, or errors in dispensing medications. The system can provide a full audit trail, allowing healthcare providers to track which staff members accessed or used specific items and ensuring that all inventory movements are properly recorded for accountability. By adopting effective inventory tracking for medicines and supplies, healthcare organizations can improve operational efficiency, reduce costs, ensure patient safety, and ultimately provide better care, all while maintaining a high level of regulatory compliance.",
      buttonText: "Get Started",
    },
    {
      title: "Telemedicine Integration",
      description: " Facilitating online consultations and follow-ups is a modern approach that significantly enhances healthcare delivery by providing patients with convenient, accessible, and efficient means of receiving medical care. With the rise of telemedicine platforms, healthcare providers can offer consultations to patients remotely, eliminating geographic barriers and allowing for more flexible scheduling. This is especially beneficial for patients who may have difficulty traveling due to health conditions, distance, or time constraints. Through secure video calls, chat functions, or voice consultations, patients can easily communicate with healthcare professionals, share symptoms, and discuss their health concerns from the comfort of their homes. Additionally, online consultations enable healthcare providers to conduct preliminary assessments, provide advice, prescribe medications, and even diagnose conditions, all through a secure, confidential digital platform. This accessibility not only improves patient satisfaction but also helps to reduce the burden on in-person appointments, making healthcare more efficient and responsive. Follow-up consultations are equally important and can be easily managed through online platforms, ensuring that patients receive continuous care and attention without needing to revisit the healthcare facility in person. Automated reminders and appointment scheduling features can be integrated into the system, helping to ensure patients don’t miss their follow-up appointments. Furthermore, healthcare providers can review patient records, track progress, and monitor ongoing treatments through the platform, allowing for personalized follow-up care. This streamlines the care process by eliminating the need for paper-based records or manual tracking, offering a more organized and efficient method for managing patient care over time. The online consultation model also reduces the risk of exposure to contagious diseases by minimizing the need for in-person visits, offering a safer alternative for both patients and healthcare professionals. Additionally, digital platforms can offer secure messaging features, allowing patients to ask questions, share test results, or clarify medical instructions between consultations, ensuring continuous communication. By facilitating online consultations and follow-ups, healthcare organizations can reach a broader patient base, improve patient engagement, enhance the quality of care, and reduce overhead costs associated with traditional in-person appointments. This approach ultimately promotes a more flexible, accessible, and patient-centered healthcare experience.",
      buttonText: "Get Started",
    },
    {
      title: " Waste Management",
      description: "Optimizing resource utilization and reducing waste is a critical strategy for improving efficiency, sustainability, and cost-effectiveness in any organization, particularly in sectors like healthcare, manufacturing, and retail. By implementing advanced resource management techniques, businesses can ensure that resources such as time, labor, materials, and energy are allocated in the most effective way possible, minimizing unnecessary expenditures and environmental impact. In healthcare, for example, optimizing resource utilization means ensuring that medical staff, equipment, and pharmaceuticals are used effectively to deliver the best patient care without overutilizing or underutilizing resources. Implementing predictive analytics and demand forecasting helps healthcare facilities anticipate patient volumes, allowing them to adjust staffing levels and ensure that critical supplies are available without overstocking, which can lead to waste due to expiration or obsolescence. In manufacturing, optimizing the use of raw materials, machinery, and labor reduces production costs, enhances throughput, and minimizes the generation of defective products or scrap materials. Lean manufacturing principles, such as just-in-time production and continuous improvement, focus on eliminating inefficiencies and reducing waste by streamlining processes, reducing bottlenecks, and minimizing inventory holding costs. In the retail industry, optimization of inventory management ensures that products are replenished in accordance with demand, preventing overstocking or stockouts that lead to waste or missed sales opportunities. Moreover, reducing waste in the workplace or production environments not only contributes to environmental sustainability but also has a direct financial benefit, as it lowers operational costs, increases profitability, and enhances the organization’s reputation as a responsible corporate entity. Digital technologies such as Internet of Things (IoT) sensors, data analytics, and automation tools can play a pivotal role in tracking resource consumption, identifying inefficiencies, and providing real-time insights that enable businesses to make data-driven decisions to optimize their operations. For example, energy monitoring systems can help businesses track their energy consumption patterns and identify areas for improvement, such as upgrading inefficient equipment or implementing energy-saving measures. Additionally, waste management solutions can help businesses track the disposal of materials, optimize recycling efforts, and minimize the environmental footprint. By focusing on optimizing resource utilization and reducing waste, organizations can achieve significant cost savings, enhance operational efficiency, improve customer satisfaction, and contribute to sustainability efforts, ensuring long-term success and resilience in an increasingly competitive and environmentally conscious marketplace.",
      buttonText: "Get Started",
    },
    
 
  ];

  return (
    <div style={{backgroundColor:"#f5f5f5",position:"relative",marginTop:"-24px" }}>
      <h2 style={{textAlign:"center", fontSize:"30px", paddingTop: 40, backgroundColor:"#f5f5f5"}}>Beelinx Products</h2>
      <p style={{textAlign:"center", fontSize:"20px", paddingBottom: 40 , paddingTop:20,backgroundColor:"#f5f5f5"}}>Innovative Financial Solutions for Seamless Integration, Efficiency, and Growth.</p>
    <section className={styles.driveEfficiencySection}>
      {/* Static Video */}
      <div className={styles.staticVideoContainer}>
        <video
          src="/Beelinx_features_demo.mp4" // Correct path to public folder
          className={styles.staticVideo}
          autoPlay
          loop
          muted
        >
          Your browser does not support the video tag.
        </video>
      </div>

      {/* Scrolling Content */}
      <div className={styles.contentContainer}>
        {content.map((item, index) => (
          <div className={styles.contentBlock} key={index}>
            <h3>{item.title}</h3>
            <p>{item.description}</p>
            <button className={styles.button}>{item.buttonText}</button>
          </div>
        ))}
      </div>
    </section>
    </div>
  );
};

export default HMSScrollSection;
